language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=mindstorm-ev3
    - DEPOPTS="*"
  matrix:
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
cache:
  directories:
    - $HOME/.opam
